#cloud-config
autoinstall:
  version: 1

  identity:
    realname: Leandro
    hostname: leandro
    username: leandro
    password: "$6$rounds=4096$k9VbQ2mX7pLwZr8F$Y5cQz3m9Jf0xK2pQv7Zs8dW4rT1bN6uHj3Lk8Pq2mVx5Cz9sQw1Xy7Fz0Rk6Jp3LmN8vT2cQ4bY7Zr5W1p0"

  locale: pt_BR.UTF-8

  keyboard:
    layout: br
    variant: ""

  timezone: America/Araguaina

  ssh:
    install-server: true
    allow-pw: true

  packages:
    - libreoffice
    - gimp
    - vlc
    - ufw

  snaps:
    - name: spotify
      channel: stable

  codecs:
    install: true

  drivers:
    install: true

  updates: all

  late-commands:
    - curtin in-target --target=/target ufw enable

  shutdown: reboot
