#cloud-config
autoinstall:
  version: 1
  identity:
    realname: 'Leandro'
    hostname: z1tsp01dt10
    username: leandro
    password: '$6$rounds=4096$...'

  locale: pt_BR.utf8

  keyboard:
    layout: br

  timezone: America/Araguaina

  ssh:
    install-server: true
    allow-pw: true

  packages:
    - libreoffice
    - gimp
    - vlc
    - ufw

  snaps:
    - name: spotify
      channel: stable

  codecs:
    install: true

  drivers:
    install: true

  updates: all

  late-commands:
    - curtin in-target --target=/target ufw enable

  shutdown: reboot
